### ISSUE TITLE
checkArticleExists throwing on error

### ISSUE THREAD

**Issue by hughrun** [hughrun/rockpool#75]
**Describe the bug**
For unclear reasons, occassionally checkArticleExists throws with an `MongoNetworkError: write EPIPE` error. Whilst this deserves its own investigation, the bigger issue is that this is a show-stopping throw rather than an error that is merely reported to log.

**To Reproduce**
No sure, presumably this is coming from the feed-checking function.

**Expected behavior**
When error occurs in `checkArticleExists` it is logged to console and app continues on.

**Error message**
```
/usr/src/app/node_modules/mongodb/lib/topologies/server.js:240
            throw err;
            ^

AssertionError [ERR_ASSERTION]: null === 'MongoNetworkError: write EPIPE'
    at /usr/src/app/lib/queries.js:337:14
    at err (/usr/src/app/node_modules/mongodb/lib/utils.js:411:14)
    at executeCallback (/usr/src/app/node_modules/mongodb/lib/utils.js:401:25)
    at err (/usr/src/app/node_modules/mongodb/lib/operations/mongo_client_ops.js:285:21)
    at connectCallback (/usr/src/app/node_modules/mongodb/lib/operations/mongo_client_ops.js:265:5)
    at server.connect (/usr/src/app/node_modules/mongodb/lib/operations/mongo_client_ops.js:353:14)
    at Server.<anonymous> (/usr/src/app/node_modules/mongodb/lib/topologies/server.js:237:11)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at Pool.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/topologies/server.js:452:12)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at connect (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:557:14)
    at callback (/usr/src/app/node_modules/mongodb-core/lib/connection/connect.js:109:5)
    at runCommand (/usr/src/app/node_modules/mongodb-core/lib/connection/connect.js:129:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rockpool-app@1.0.0 start: `NODE_ENV=production node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rockpool-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-05T04_06_32_552Z-debug.log
```

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by hughrun** [comment]
possibly need a `return` at feeds.js line 177
